// source: RequestLiveStream.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.goproto.EnumRegisterLiveStreamStatus', null, global);
goog.exportSymbol('proto.goproto.RequestGetLiveStreamStatus', null, global);
goog.exportSymbol('proto.goproto.RequestLiveStream', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.goproto.RequestLiveStream = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.goproto.RequestLiveStream, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.goproto.RequestLiveStream.displayName = 'proto.goproto.RequestLiveStream';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.goproto.RequestGetLiveStreamStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.goproto.RequestGetLiveStreamStatus.repeatedFields_, null);
};
goog.inherits(proto.goproto.RequestGetLiveStreamStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.goproto.RequestGetLiveStreamStatus.displayName = 'proto.goproto.RequestGetLiveStreamStatus';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.goproto.RequestLiveStream.prototype.toObject = function(opt_includeInstance) {
  return proto.goproto.RequestLiveStream.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.goproto.RequestLiveStream} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.goproto.RequestLiveStream.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    encode: (f = jspb.Message.getBooleanField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.goproto.RequestLiveStream}
 */
proto.goproto.RequestLiveStream.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.goproto.RequestLiveStream;
  return proto.goproto.RequestLiveStream.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.goproto.RequestLiveStream} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.goproto.RequestLiveStream}
 */
proto.goproto.RequestLiveStream.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEncode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.goproto.RequestLiveStream.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.goproto.RequestLiveStream.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.goproto.RequestLiveStream} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.goproto.RequestLiveStream.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.goproto.RequestLiveStream.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.goproto.RequestLiveStream} returns this
 */
proto.goproto.RequestLiveStream.prototype.setUrl = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.goproto.RequestLiveStream} returns this
 */
proto.goproto.RequestLiveStream.prototype.clearUrl = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.goproto.RequestLiveStream.prototype.hasUrl = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool encode = 2;
 * @return {boolean}
 */
proto.goproto.RequestLiveStream.prototype.getEncode = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.goproto.RequestLiveStream} returns this
 */
proto.goproto.RequestLiveStream.prototype.setEncode = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.goproto.RequestLiveStream} returns this
 */
proto.goproto.RequestLiveStream.prototype.clearEncode = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.goproto.RequestLiveStream.prototype.hasEncode = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.goproto.RequestGetLiveStreamStatus.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.goproto.RequestGetLiveStreamStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.goproto.RequestGetLiveStreamStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.goproto.RequestGetLiveStreamStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.goproto.RequestGetLiveStreamStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    registerLiveStreamStatusList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    unregisterLiveStreamStatusList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.goproto.RequestGetLiveStreamStatus}
 */
proto.goproto.RequestGetLiveStreamStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.goproto.RequestGetLiveStreamStatus;
  return proto.goproto.RequestGetLiveStreamStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.goproto.RequestGetLiveStreamStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.goproto.RequestGetLiveStreamStatus}
 */
proto.goproto.RequestGetLiveStreamStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<!proto.goproto.EnumRegisterLiveStreamStatus>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRegisterLiveStreamStatus(values[i]);
      }
      break;
    case 2:
      var values = /** @type {!Array<!proto.goproto.EnumRegisterLiveStreamStatus>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addUnregisterLiveStreamStatus(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.goproto.RequestGetLiveStreamStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.goproto.RequestGetLiveStreamStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.goproto.RequestGetLiveStreamStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.goproto.RequestGetLiveStreamStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRegisterLiveStreamStatusList();
  if (f.length > 0) {
    writer.writeRepeatedEnum(
      1,
      f
    );
  }
  f = message.getUnregisterLiveStreamStatusList();
  if (f.length > 0) {
    writer.writeRepeatedEnum(
      2,
      f
    );
  }
};


/**
 * repeated EnumRegisterLiveStreamStatus register_live_stream_status = 1;
 * @return {!Array<!proto.goproto.EnumRegisterLiveStreamStatus>}
 */
proto.goproto.RequestGetLiveStreamStatus.prototype.getRegisterLiveStreamStatusList = function() {
  return /** @type {!Array<!proto.goproto.EnumRegisterLiveStreamStatus>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<!proto.goproto.EnumRegisterLiveStreamStatus>} value
 * @return {!proto.goproto.RequestGetLiveStreamStatus} returns this
 */
proto.goproto.RequestGetLiveStreamStatus.prototype.setRegisterLiveStreamStatusList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!proto.goproto.EnumRegisterLiveStreamStatus} value
 * @param {number=} opt_index
 * @return {!proto.goproto.RequestGetLiveStreamStatus} returns this
 */
proto.goproto.RequestGetLiveStreamStatus.prototype.addRegisterLiveStreamStatus = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.goproto.RequestGetLiveStreamStatus} returns this
 */
proto.goproto.RequestGetLiveStreamStatus.prototype.clearRegisterLiveStreamStatusList = function() {
  return this.setRegisterLiveStreamStatusList([]);
};


/**
 * repeated EnumRegisterLiveStreamStatus unregister_live_stream_status = 2;
 * @return {!Array<!proto.goproto.EnumRegisterLiveStreamStatus>}
 */
proto.goproto.RequestGetLiveStreamStatus.prototype.getUnregisterLiveStreamStatusList = function() {
  return /** @type {!Array<!proto.goproto.EnumRegisterLiveStreamStatus>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<!proto.goproto.EnumRegisterLiveStreamStatus>} value
 * @return {!proto.goproto.RequestGetLiveStreamStatus} returns this
 */
proto.goproto.RequestGetLiveStreamStatus.prototype.setUnregisterLiveStreamStatusList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!proto.goproto.EnumRegisterLiveStreamStatus} value
 * @param {number=} opt_index
 * @return {!proto.goproto.RequestGetLiveStreamStatus} returns this
 */
proto.goproto.RequestGetLiveStreamStatus.prototype.addUnregisterLiveStreamStatus = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.goproto.RequestGetLiveStreamStatus} returns this
 */
proto.goproto.RequestGetLiveStreamStatus.prototype.clearUnregisterLiveStreamStatusList = function() {
  return this.setUnregisterLiveStreamStatusList([]);
};


/**
 * @enum {number}
 */
proto.goproto.EnumRegisterLiveStreamStatus = {
  REGISTER_LIVE_STREAM_STATUS_STATUS: 1,
  REGISTER_LIVE_STREAM_STATUS_ERROR: 2,
  REGISTER_LIVE_STREAM_STATUS_MODE: 3,
  REGISTER_LIVE_STREAM_STATUS_BITRATE: 4
};

goog.object.extend(exports, proto.goproto);
