export const SET_GOPRO_FILES_TO_LOCAL_STORAGE =
  'SET_GOPRO_FILES_TO_LOCAL_STORAGE';

export const SET_DOWNLOADING_FILE = 'SET_DOWNLOADING_FILE';

export const SET_UPLOADING_FILE = 'SET_UPLOADING_FILE';

export const SET_DIR_NAME_TO_DOWNLOAD = 'SET_DIR_NAME_TO_DOWNLOAD';
export const SET_DOWNLOADED_COMPLETED = 'SET_DOWNLOADED_COMPLETED';
export const SET_UPLOADEDED_COMPLETED = 'SET_UPLOADEDED_COMPLETED';
export const SET_SESSION_DETAILS = 'SET_SESSION_DETAILS';

export const SET_GOPRO_MEDIA = 'SET_GOPRO_MEDIA';

export const SET_DOWNLOAD_MEDIA_PROGRESS = 'SET_DOWNLOAD_MEDIA_PROGRESS';
export const SET_UPLOAD_MEDIA_PROGRESS = 'SET_UPLOAD_MEDIA_PROGRESS';

export const COMPLETED_DOWNLOADED_FILE = 'COMPLETED_DOWNLOADED_FILE';

export const COMPLETED_UPLOADED_FILE = 'COMPLETED_UPLOADED_FILE';
export const SET_SCHEDULED_SESSIONS = 'SET_SCHEDULED_SESSIONS';
