export const SET_GOPRO_FILES_TO_LOCAL_STORAGE =
  'SET_GOPRO_FILES_TO_LOCAL_STORAGE';

export const SET_DOWNLOADING_FILE = 'SET_DOWNLOADING_FILE';

export const SET_UPLOADING_FILE = 'SET_UPLOADING_FILE';

export const SET_DIR_NAME_TO_DOWNLOAD = 'SET_DIR_NAME_TO_DOWNLOAD';
export const SET_DOWNLOADED_COMPLETED = 'SET_DOWNLOADED_COMPLETED';
export const SET_UPLOADEDED_COMPLETED = 'SET_UPLOADEDED_COMPLETED';
export const SET_SESSION_DETAILS = 'SET_SESSION_DETAILS';
