export const DOWNLOAD_MEDIA = 'DOWNLOAD_MEDIA';
export const DOWNLOAD_MEDIA_FAILED = 'DOWNLOAD_MEDIA_FAILED';
export const DOWNLOAD_MEDIA_SUCCESS = 'DOWNLOAD_MEDIA_SUCCESS';
export const DOWNLOAD_MEDIA_PROGRESS = 'DOWNLOAD_MEDIA_PROGRESS';
export const RESET_DOWNLOAD_MEDIA = 'RESET_DOWNLOAD_MEDIA';
export const UPLOAD_MEDIA_SUCCESS = 'UPLOAD_MEDIA_SUCCESS';
export const UPLOAD_MEDIA_FAILED = 'UPLOAD_MEDIA_FAILED';
export const UPLOAD_MEDIA = 'UPLOAD_MEDIA';

export const UPLOAD_MEDIA_PROGRESS = 'UPLOAD_MEDIA_PROGRESS';
